### ISSUE TITLE
Write-up of project proposal

### ISSUE THREAD

**Issue by hlac** [chensourceforge/MockCentennial#10]
In the wiki: 
- Background
- Literature Review 
- Proposed Project
- Architecture (usually consists of perspective from different stakeholders, but for our purposes the developer view is most important).

**Comment by Icefrenzy** [comment]
Completed most of the proposal except for the Architecture.

Src: https://github.com/chensourceforge/MockCentennial/wiki/Home---Project-Proposal

**Comment by Icefrenzy** [comment]
Use Case Diagram added at Wiki page. Will be adding detailed list and descriptions after meeting this week.

Src: https://github.com/chensourceforge/MockCentennial/wiki/Use-Case

**Comment by Icefrenzy** [comment]
Updated Use Case wiki page with brief descriptions. Will be adding the detailed descriptions tonight.
Src: https://github.com/chensourceforge/MockCentennial/wiki/Use-Case

**Comment by Icefrenzy** [comment]
Delaying Use Case detailed descriptions until after meeting for confirmation.
Src: https://github.com/chensourceforge/MockCentennial/wiki/Use-Case

**Comment by Icefrenzy** [comment]
Reorganized Use Case brief descriptions priority listing.
Src: https://github.com/chensourceforge/MockCentennial/wiki/Use-Case
