### ISSUE TITLE
Group Meetings

### ISSUE THREAD

**Issue by ahmedb7** [chensourceforge/MockCentennial#12]
Please attend group meetings
We had planned to meet up this friday at 12.30 to 2.30pm
and only 4 people showed up

**Comment by hlac** [comment]
Please list names of absentees in future emails.


Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by ahmedb7** [comment]
Group Meeting Monday 2017
Distributed project work:
- Registration system, assigns semester -done
- timetable algorithm - viranch and joni, adil( database)
- waiting list : Kevin, Benzir
- modify timetable - later, once algorithm is done
- UI – Summy, ravinder , Benzir
- Admin: ask professor how to implement?

**Comment by hlac** [comment]
Using issues to schedule meetings is odd.  Also, work should be self
assigned after stories and tasks are disaggregated.


Regards,
Hao C. Lac, Ph.D. (Computational Science)
