### ISSUE TITLE
Design Student object

### ISSUE THREAD

**Issue by hlac** [chensourceforge/MockCentennial#6]
Think about attributes related to a Student object that would be helpful for the system when it makes its decision.

**Comment by hlac** [comment]
#9

**Comment by hlac** [comment]
UML class diagram is required for this issue.

**Comment by AdilHussain919** [comment]
![studentclass](https://cloud.githubusercontent.com/assets/23314831/23324738/c5e7e8a0-fabd-11e6-9396-a5f69dd1c398.PNG)
