### ISSUE TITLE
Design TimeTable object

### ISSUE THREAD

**Issue by hlac** [chensourceforge/MockCentennial#7]
TimeTable object may reference other objects such as Course objects.

TimeTable objects will have attributes that will also be used by the system.

**Comment by hlac** [comment]
#9

**Comment by hlac** [comment]
UML class diagram is required for this issue.

**Comment by AdilHussain919** [comment]
![timetableclass](https://cloud.githubusercontent.com/assets/23314831/23324753/dcbb49a0-fabd-11e6-8186-cb0dbf87924d.PNG)
